version: "0.2"
ignorePaths:
  - dist
  - node_modules
dictionaries:
  - en_US
  - softwareTerms
  - bash
  - node
  - npm
  - typescript
  - filetypes
words:
  - listhen
  - openai
ignoreWords:
  - trivago
  - zhengxs
